### PR TITLE
Anonymous review

### PR DESCRIPTION
**Pull request by kosumin**
Related Issue: #154 #141

# Major changes

1. Change subscription util so that when a user writes an anonymous review, it would not pass to others' subscription feeds.

# Minor changes

1. Make Review Card and Review Detail handle anonymous review.

(Main Feed)
image

image

(History Page)
image

(Review Detail Page) 

- my anonymous review -
image

- others' anonymous review -
image

2. CSS Change

(PaperDetail) : Add -> Create, Review Card Components, Abstract fold
image

(ReviewDetail): Button Color, Space between date and title
image

(History Page): Min-height for background
image

(Profile Detail): Collection-Review Count
image

### Checklist
This pull request...
- [x] has preceding issues related with it (if resolves some issues, metions them with 'resolve')
- [ ] doesn't include too many changes (you should focus on the specific feature in a PR)
- [x] elaborately explains what feature is added, which part is fixed or improved
- [x] has step by step instructions for collaborators, if needed
- [x] has attached screenshots, if appropriate

My codes...
- [x] include enough tests for added and changed parts
- [x] pass all the new and existing tests
- [ ] include appropriate comments
- [x] don't introduce unnecessary warnings

### CODE REVIEW

**Comment by kosumin** [comment]
When backend passes an anonymous review for recommendation or subscription, "Anonymous User" would appear on the card instead of username now(in this pr).

**Comment by davin111** [comment]
Also, in #154 PR you introduced pagination to ProfileDetail. I think you should also make the counts of collections and reviews on each tab reflect the real total count in DB. For now, they just reflect the lengths of state arrays.

**Comment by kosumin** [comment]
Do you want it never to go to main feed?

**Comment by davin111** [comment]
Also, in #154 PR you introduced pagination to ProfileDetail. I think you should also make the counts of collections and reviews on each tab reflect the real total count in DB. For now, they just reflect the lengths of state arrays.

**Comment by davin111** [comment]
> Do you want it never to go to main feed?

Well, now I can understand your point. But isn't is unnatural that some users can get subscription about anonymous reviews? Because they can know someone who they are following wrote them.

**Pull request merged**
